In [ ]:
# link to tutorial: https://www.datacamp.com/tutorial/python-numpy-tutorial

In [ ]:
import numpy as np
# one dimensional array definition
one_d_array = np.array([1,2,3,4],
                      dtype=np.int64)

In [ ]:
one_d_array

array([1, 2, 3, 4])

In [ ]:
one_d_array.shape

(4,)

In [ ]:
# two dimensional array definition
two_d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]],
                       dtype=np.int64)

In [ ]:
two_d_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
two_d_array.shape

(2, 4)

In [ ]:
# three dimension array definition
three_d_array = np.array([[[1,2,3,4],
                           [5,6,7,8]],
                          [[1,2,3,4],
                           [9, 10, 11, 12]]],
                         dtype=np.int64)

In [ ]:
three_d_array.shape

(2, 2, 4)

In [ ]:
print(one_d_array)

[1 2 3 4]


In [ ]:
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(three_d_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [ ]:
two_d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# print the mememory address
print("Memory address:", two_d_array.data)
print("Array shape:", two_d_array.shape)
print("Array data type:", two_d_array.dtype)
print("Stride of the array:", two_d_array.strides)

Memory address: <memory at 0x7c4bf323fb90>
Array shape: (2, 4)
Array data type: int64
Stride of the array: (32, 8)


In [ ]:
test_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("Test array:")
print(test_array)

Test array:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# creating an array with ones
array_with_ones = np.ones((3,4))
print("array_with_ones:")
print(array_with_ones)

array_with_ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# creating an array with zeros
array_with_zeros = np.zeros((2, 3, 4), dtype=np.int16)
print("array with zeros:")
print(array_with_zeros)

array with zeros:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# creating an array with random values
array_with_random_values = np.random.random((2,2))
print("array with random values:")
print(array_with_random_values)

array with random values:
[[0.7252345  0.00349828]
 [0.92110458 0.52065876]]


In [ ]:
# creating an array with no values (empty array)
array_with_no_values = np.empty((3, 2))
print("array with no values:")
print(array_with_no_values)

array with no values:
[[2.87047458e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
# creating an array filled with values
full_array = np.full((2,2), 7)
print("full array:")
print(full_array)

full array:
[[7 7]
 [7 7]]


In [ ]:
# creating an array with evenly spaced values
arange_array = np.arange(0, 15, 5)
print("arange array:")
print(arange_array)

arange array:
[ 0  5 10]


In [ ]:
arange_array_two = np.linspace(0,2,9)
print("arange array two:")
print(arange_array_two)

arange array two:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# if your data file looks like this
###################################
# This is your data in the text file
# Value1  Value2  Value3
# 0.2536  0.1008  0.3857
# 0.4839  0.4536  0.3561
# 0.1292  0.6875  0.5929
# 0.1781  0.3049  0.8928
# 0.6253  0.3486  0.8791

# you can import it like this:
x, y, z = np.loadtxt('data.txt',
                     skiprows=1,
                     unpack=True)

In [ ]:
# if your data file looks like this
###################################
# Your data in the text file
# Value1  Value2  Value3
# 0.4839  0.4536  0.3561
# 0.1292  0.6875  MISSING
# 0.1781  0.3049  0.8928
# MISSING 0.5801  0.2038
# 0.5993  0.4357  0.7410

# you can import it like this
input_array = np.genfromtxt('data.txt',
                            skip_header=1,
                            filling_values=-999)

In [ ]:
# save numpy arrays
x = np.arange(0.0, 5.0, 1.0)
np.savetxt('test.out', x, delimiter=',')

In [ ]:
ls

sample_data/  test.out


In [ ]:
# inspect your arrays

# create an array with the shape (2,4) and int64 datatype

array_a = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

In [ ]:
# get the number of dimensions of the array
print("Array dimensions:", array_a.ndim)

Array dimensions: 2


In [ ]:
# get the number of elements in the array
print("Array size:", array_a.size)

Array size: 8


In [ ]:
# get array information about memory layout
print("Array memory layout:", array_a.flags)

Array memory layout:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
# get the length of one array element in bytes
print("Array item size:", array_a.itemsize)

Array item size: 8


In [ ]:
# get the number of total consumed bytes by the array elements
print("total consumed bytes by the array:", array_a.nbytes)

total consumed bytes by the array: 64


In [ ]:
# print the length of the array
print("Array length:", len(array_a))

Array length: 2


In [ ]:
# change the data type of the array to float
array_a.astype(np.float32)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [ ]:
#broadcasting numpy arrays
#create a 3x4 array with ones
array_x = np.ones((3,4))
print("Shape of array_x:", array_x.shape)

Shape of array_x: (3, 4)


In [ ]:
# create a 3x4 array with random numbers
array_y = np.random.random((3,4))
print("array_y shape:", array_y.shape)

array_y shape: (3, 4)


In [ ]:
# add the arrays x and y element wise
array_z = array_x + array_y
print("result of x + y:\n", array_z)
print("shape of x + y:", array_z.shape)

result of x + y:
 [[1.41574261 1.70283717 1.50916979 1.89770955]
 [1.17426614 1.97716136 1.80579669 1.59902368]
 [1.76870284 1.60337829 1.37179365 1.23708325]]
shape of x + y: (3, 4)


In [ ]:
# if dimensions of the arrays are compatible only then they can be broadcast together
array_x = np.ones((3,4))
array_y = np.random.random((5,1,4))
array_z = array_x + array_y

In [ ]:
# the reason addition works is because they are compatible 3 x 4 array with 5 x 1 x 4 array
array_z

array([[[1.4484775 , 1.23620622, 1.52659127, 1.73423808],
        [1.4484775 , 1.23620622, 1.52659127, 1.73423808],
        [1.4484775 , 1.23620622, 1.52659127, 1.73423808]],

       [[1.99764817, 1.16859689, 1.31242314, 1.81139029],
        [1.99764817, 1.16859689, 1.31242314, 1.81139029],
        [1.99764817, 1.16859689, 1.31242314, 1.81139029]],

       [[1.09681799, 1.9324461 , 1.05437422, 1.8567809 ],
        [1.09681799, 1.9324461 , 1.05437422, 1.8567809 ],
        [1.09681799, 1.9324461 , 1.05437422, 1.8567809 ]],

       [[1.64384387, 1.97595262, 1.62374487, 1.58031591],
        [1.64384387, 1.97595262, 1.62374487, 1.58031591],
        [1.64384387, 1.97595262, 1.62374487, 1.58031591]],

       [[1.43223524, 1.73612582, 1.94070857, 1.23878811],
        [1.43223524, 1.73612582, 1.94070857, 1.23878811],
        [1.43223524, 1.73612582, 1.94070857, 1.23878811]]])

In [ ]:
x = np.array([[1,2,3], [3,4,5]])
y = np.array([6,7,8])

# add x + y = z
z = np.add(x,y)
print("sum of x + y:\n", z)

sum of x + y:
 [[ 7  9 11]
 [ 9 11 13]]


In [ ]:
# subtract x - y = z
z = np.subtract(x,y)
print("difference of x - y\n", z)

difference of x - y
 [[-5 -5 -5]
 [-3 -3 -3]]


In [ ]:
#multiply x and y
z = np.multiply(x,y)
print("product of x and y\n", z)

product of x and y
 [[ 6 14 24]
 [18 28 40]]


In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

# logical and
np.logical_and(a,b)

array([ True, False, False, False])

In [ ]:
# logical or
np.logical_or(a,b)

array([ True,  True,  True, False])

In [ ]:
# logical a not b
np.logical_not(a,b)

array([False, False,  True,  True])

In [ ]:
c = np.logical_not(a)
c

array([False, False,  True,  True])

In [2]:
# subsetting
import numpy as np
x = np.array([1,2,3,4])
print(x[1])

2


In [5]:
# create a 2d array
y = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(y[1][2])
print(y[1,2])

7
7


In [6]:
# create a 3d array
z = np.array([[[1,2,3,4], [5,6,7,8]], [[9, 10, 11, 12],[13, 14, 15, 16]]], dtype=np.int64)
print(z[1,1,2])

15


In [ ]:
# slicing
x = np.array([1,2,3,4])
print(x[0:2])

[1 2]


In [ ]:
y = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(y[0:2, 1])

[2 6]


In [ ]:
print(z[1,...])

[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# a[start:end] items start through the end (but the end is not included)
# a[start:]  items start through the rest of the array
# a[:end] items from the beginning through the end (but the end is not included)

In [ ]:
#indexing
print(x[x<2])

[1]


In [ ]:
# condition
greater_than_three = (z >= 3)
print(z[greater_than_three])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# select elements at (1,0), (0,1), (1,2) and (0,0)
print("first",y[[1,0,1,0]])
# select a subset of the rows and columns
print("second",y[[1,0,1,0]][:,[0,1,2,0]])

first [[5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]
second [[5 6 7 5]
 [1 2 3 1]
 [5 6 7 5]
 [1 2 3 1]]


In [ ]:
print(np.lookfor("mean"))

AttributeError: `np.lookfor` was removed in the NumPy 2.0 release. Search NumPy's documentation directly.

In [ ]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [ ]:
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# transpose
np.transpose(y)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [8]:
# to transpose an array you can also do this:
print(y.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [11]:
# trying to transpose a one d array
print(x)
print("x transposed:", x.T)
# there is no effect on a one dimensional array

[1 2 3 4]
x transposed: [1 2 3 4]


In [14]:
# to do arithmetic with arrays you might have to resize them
d = np.ones((3,4))
print(d.shape)
print(d)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# resize them
np.resize(d, (6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
d.resize((6,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# arrays can be reshaped as well
d = np.ones((3,4))
print("array d shape:", d.shape)

array d shape: (3, 4)


In [20]:
np.resize(d, (6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
d.resize((6,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# shape of aray before transposing
print("array before transposing", d)
print("shape of array before transposing", d.shape)

array before transposing [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape of array before transposing (6, 4)


In [24]:
# transpose the array
d = d.T
print("array after transposing", d)
print("shape of array after transposing", d.shape)

array after transposing [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
shape of array after transposing (4, 6)


In [26]:
# appending arrays
# creating a new array
x = np.array([1,2,3,4])
print("array before appending", x)
# append the array
appended_array = np.append(x, [5,6,7,8])
print("array after appending", appended_array)
print("original array after appending", x)

array before appending [1 2 3 4]
array after appending [1 2 3 4 5 6 7 8]
original array after appending [1 2 3 4]


In [30]:
# appending two dimensional arrays
print("2d array before appending:\n", y)
# axis 1 indicates columns and axis 0 indicates rows in 2 d arrays
appended_two_d_array = np.append(y, [[10], [11]], axis=1)
print("appended two d array:\n", appended_two_d_array)
print("original two d array:\n", y)

2d array before appending:
 [[1 2 3 4]
 [5 6 7 8]]
appended two d array:
 [[ 1  2  3  4 10]
 [ 5  6  7  8 11]]
original two d array:
 [[1 2 3 4]
 [5 6 7 8]]
