In [3]:
# link to tutorial: https://www.datacamp.com/tutorial/python-numpy-tutorial

In [4]:
import numpy as np
# one dimensional array definition
one_d_array = np.array([1,2,3,4],
                      dtype=np.int64)

In [5]:
one_d_array

array([1, 2, 3, 4])

In [6]:
one_d_array.shape

(4,)

In [7]:
# two dimensional array definition
two_d_array = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]],
                       dtype=np.int64)

In [8]:
two_d_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
two_d_array.shape

(2, 4)

In [10]:
# three dimension array definition
three_d_array = np.array([[[1,2,3,4],
                           [5,6,7,8]],
                          [[1,2,3,4],
                           [9, 10, 11, 12]]],
                         dtype=np.int64)

In [14]:
three_d_array.shape

(2, 2, 4)

In [11]:
print(one_d_array)

[1 2 3 4]


In [12]:
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
print(three_d_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [20]:
two_d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# print the mememory address
print("Memory address:", two_d_array.data)
print("Array shape:", two_d_array.shape)
print("Array data type:", two_d_array.dtype)
print("Stride of the array:", two_d_array.strides)

Memory address: <memory at 0x7c4bf323fb90>
Array shape: (2, 4)
Array data type: int64
Stride of the array: (32, 8)


In [22]:
test_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("Test array:")
print(test_array)

Test array:
[[1 2 3 4]
 [5 6 7 8]]


In [23]:
# creating an array with ones
array_with_ones = np.ones((3,4))
print("array_with_ones:")
print(array_with_ones)

array_with_ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
# creating an array with zeros
array_with_zeros = np.zeros((2, 3, 4), dtype=np.int16)
print("array with zeros:")
print(array_with_zeros)

array with zeros:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [27]:
# creating an array with random values
array_with_random_values = np.random.random((2,2))
print("array with random values:")
print(array_with_random_values)

array with random values:
[[0.7252345  0.00349828]
 [0.92110458 0.52065876]]


In [30]:
# creating an array with no values (empty array)
array_with_no_values = np.empty((3, 2))
print("array with no values:")
print(array_with_no_values)

array with no values:
[[2.87047458e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [31]:
# creating an array filled with values
full_array = np.full((2,2), 7)
print("full array:")
print(full_array)

full array:
[[7 7]
 [7 7]]


In [35]:
# creating an array with evenly spaced values
arange_array = np.arange(0, 15, 5)
print("arange array:")
print(arange_array)

arange array:
[ 0  5 10]


In [36]:
arange_array_two = np.linspace(0,2,9)
print("arange array two:")
print(arange_array_two)

arange array two:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# if your data file looks like this
###################################
# This is your data in the text file
# Value1  Value2  Value3
# 0.2536  0.1008  0.3857
# 0.4839  0.4536  0.3561
# 0.1292  0.6875  0.5929
# 0.1781  0.3049  0.8928
# 0.6253  0.3486  0.8791

# you can import it like this:
x, y, z = np.loadtxt('data.txt',
                     skiprows=1,
                     unpack=True)

In [ ]:
# if your data file looks like this
###################################
# Your data in the text file
# Value1  Value2  Value3
# 0.4839  0.4536  0.3561
# 0.1292  0.6875  MISSING
# 0.1781  0.3049  0.8928
# MISSING 0.5801  0.2038
# 0.5993  0.4357  0.7410

# you can import it like this
input_array = np.genfromtxt('data.txt',
                            skip_header=1,
                            filling_values=-999)

In [37]:
# save numpy arrays
x = np.arange(0.0, 5.0, 1.0)
np.savetxt('test.out', x, delimiter=',')

In [40]:
ls

sample_data/  test.out


In [47]:
# inspect your arrays

# create an array with the shape (2,4) and int64 datatype

array_a = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

In [50]:
# get the number of dimensions of the array
print("Array dimensions:", array_a.ndim)

Array dimensions: 2


In [52]:
# get the number of elements in the array
print("Array size:", array_a.size)

Array size: 8


In [53]:
# get array information about memory layout
print("Array memory layout:", array_a.flags)

Array memory layout:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [54]:
# get the length of one array element in bytes
print("Array item size:", array_a.itemsize)

Array item size: 8


In [55]:
# get the number of total consumed bytes by the array elements
print("total consumed bytes by the array:", array_a.nbytes)

total consumed bytes by the array: 64


In [59]:
# print the length of the array
print("Array length:", len(array_a))

Array length: 2


In [61]:
# change the data type of the array to float
array_a.astype(np.float32)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)