In [1]:
# link to tutorial: https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
# tensors are specialized data structures that are similar to arrays
# and matries. in pytorch use tensors to encode the inputs and outputs
# of a model as well as model parameters
# tensors are similar to numpy's ndarrays except that tensors can run 
# on gpus or other hardware accelerators
# tensors and numpy arrays share the same underlying memory, eliminating
# the need to copy data. tensors are also optimized for automatic 
# differentiation.

In [1]:
import torch
import numpy as np 

In [4]:
# initializing a tensor. tensors can be initialized in various ways
# directly from data 
# tensors can be created directly from data.
# this data type is automatically inferred.

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [5]:
# tensors can also be created from numpy arrays
np_array = np.array(data)
X_np = torch.from_numpy(np_array)

In [6]:
# tensors can also be created from another tensor
# the new tensor retains the properties of(shape, datatype) of the 
# argument tensor unless explicitly overriden.
x_ones = torch.ones_like(x_data)
# retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
# overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8269, 0.5505],
        [0.2745, 0.1154]]) 



In [2]:
# with random or constant values 
# shape is a tuple of tensor dimensions.
# in the function below it determines the dimensionality
# of the output tensor

shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor}")

Random tensor: 
 tensor([[0.9343, 0.0637, 0.9229],
        [0.8469, 0.8299, 0.3620]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# attributes of a tensor 
# tensor attributes describe their shape, datatype and the device 
# on which they are stored 

tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
device tensor is stored on: cpu


In [4]:
# operations on tensors
# by default tensors are created on the cpu, you need to explicitly move 
# tensors to the accelerator using .to method (after checking for 
# accelerator availability). keep in mind that copying large tensors
# across devices can be expensive in terms of time and memory

# we move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

AttributeError: module 'torch' has no attribute 'accelerator'

In [5]:
# indexing and slicing tensor
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [6]:
# joining tensors: you can use torch.cat to concatenate a sequence of 
# tensors along a given dimension

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [7]:
# arithmetic operations
# computes the matrix multiplication between two tensors
# tensor.T returns the transpose of a tensor
